server:
  port: 8777
#这就是第一种配置路由
#spring:
#  application:
#    name: api-gateway
#  cloud:
#    gateway:
#      routes:
#        - id: gateway-service
#          uri: https://blog.csdn.net
#          predicates:
#            - Path=/meteor_93