spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: admin
  main:
    allow-bean-definition-overriding: true
server:
  port: 8181
mybatis-plus:
  mapper-locations: classpath*:com/example/springbootelasearch/elas/mapper/xml/*.xml
  type-aliases-package: com.example.springbootelasearch.elas.mapper
# 自定义jwt key
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mySecret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头
# OSS相关配置信息
aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com # oss对外服务的访问域名
    accessKeyId: LTAI4GHgYFrU1NEMEyViWe7K
    accessKeySecret: dk8R0KzevJBAnDBVMFkZRDwsZv0rkx
    bucketName: esljh-oss
    policy:
      expire: 300 # 签名有效期(S)
    maxSize: 10 # 上传文件大小(M)
    callback: http://localhost:8080/aliyun/oss/callback # 文件上传成功后的回调地址
    dir:
      prefix: mall/images/ # 上传文件夹路径前缀
